[package]
name = "ofsvn"
version = "0.1.0"
authors = ["Magnus Larsen <golgothasTerror101@gmail.com>"]
edition = "2018"

[dependencies]
serenity = "0.8.6"
serde = "1.0.110"
serde_derive = "1.0.110"
serde_json = "1.0.53"
lazy_static = "1.4.0"
